fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
     - id: clang-format
#      - id: cppcheck
#        args: ["--language=c++", "--enable=all"]
#      - id: cpplint
#      - id: include-what-you-use